### ISSUE TITLE
Json

### ISSUE THREAD

**Issue by krulci** [Ice9Coffee/LandosolRoster#36]
能不能做个Json到对应？
Python这个在除了Python到语言想要使用的话都要自己Parse
或者做个Action自动生成Json？

**Comment by Ice9Coffee** [comment]
欢迎pr

**Comment by krulci** [comment]
> 欢迎pr

我可以把这个格式改成Json
但主要问题还是在于，后续人更新。 
如果留两个Python和Json，那如果有人只更新一个就没有意义了。

**Comment by Ice9Coffee** [comment]
action方案挺好的，监听提交自动生成，从python字典dump出json很简单的

**Comment by aJacke** [comment]
> > > 欢迎pr
> > 
> > 我可以把这个格式改成Json
> > 但主要问题还是在于，后续人更新。 
> > 如果留两个Python和Json，那如果有人只更新一个就没有意义了。 
> 
> 没事，近期基本就我在pr，我能看懂的话会顺带更（这下不得不提咕了好久的圣诞吃货了）

咕太久，我已经打算等富婆出了一起更（逃）
