### ISSUE TITLE
关于爱梅斯生日与还未填写的厄里斯简介信息

### ISSUE THREAD

**Issue by aJacke** [Ice9Coffee/LandosolRoster#52]
今天逛贴吧的时候才注意到，爱梅斯是有生日一问一答的，2月18号。游戏内还是？但实打实的是有生日的，好奇是和游戏内保持一致“？？？”，还是更新为“2月18号”。
还有一件事就是厄里斯的信息，生日看贴吧里说是redive开服时间，但我还没找到相关一问一答的内容。

**Comment by Ice9Coffee** [comment]
可以有，注释里标个出处吧
