### ISSUE TITLE
关于步美(奇幻)，步美(仙境)名称的问题

### ISSUE THREAD

**Issue by Yuk1Nok4zE** [Ice9Coffee/LandosolRoster#54]
在查询角色步美时提示无法识别"(仙境)" 您说的有90%可能是璃乃(仙境)，在项目中查询发现角色被标记为步未(仙境)，鉴于公主连结国服对角色的命名，我认为应当将"步未(仙境)"修改为"步美(仙境)",希望采纳谢谢
![`G4RW6MOQLLI ~{ SQ{{%ZW](https://github.com/user-attachments/assets/7fccc736-a9a0-4c43-b9fe-54fec4040723)
![I L07GC1V@({QHVMKJ%2CTS](https://github.com/user-attachments/assets/9837cd7c-115f-4656-b60b-bd85fb73b20d)

**Comment by Ice9Coffee** [comment]
简中服和繁中服译名差别的问题。
可以添加一个简中译名，欢迎pr

**Comment by aJacke** [comment]
已添加步美(仙境)别称
