### ISSUE TITLE
`公猫` 是不是有歧义

### ISSUE THREAD

**Issue by SaarChaffee** [Ice9Coffee/LandosolRoster#65]
公主猫拳可以叫公猫
公主凯留也可以是公猫

我建议可以把公猫删了

**Comment by sioisan** [comment]
水猫可以是夏日日和莉、春猫、

**Comment by SaarChaffee** [comment]
> 水猫也可以是夏日日和莉、夏日凯留、夏日珠希 春猫也可以是新年日和莉、新年凯留

这个基本都是叫水猫拳，水黑，水猫剑；春猫，春黑

公猫是真的不这么叫吧
